//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // /str seçeneği ile veya Visual Studio projesini yeniden kur.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Langs", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Türü kesin olarak belirtilmiş bu kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Onayla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hesap Ayarları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API Detayları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string APIDetails {
            get {
                return ResourceManager.GetString("APIDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API adı*: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string APIName {
            get {
                return ResourceManager.GetString("APIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API&apos;ler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string APIs {
            get {
                return ResourceManager.GetString("APIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API Türü*: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string APIType {
            get {
                return ResourceManager.GetString("APIType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uygulama açıklaması benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uygulama Türü*: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AppGenre {
            get {
                return ResourceManager.GetString("AppGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado Store Beta sürümünde sadece 5 uygulama yayınlamanıza izin verir. Uygulama yayınlama sınırına ulaştınız. Bağış yaparak daha fazla uygulama yayınlayabilirsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AppLimit {
            get {
                return ResourceManager.GetString("AppLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uygulamanı Artado Store&apos;da yayınlamak için başvur. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ApplyForApp {
            get {
                return ResourceManager.GetString("ApplyForApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oyununu Artado Store&apos;da yayınlamak için başvur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ApplyForGame {
            get {
                return ResourceManager.GetString("ApplyForGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado Search için geliştirdiğiniz temaları, eklentileri ve logoları yayınlamak için başvurabilirsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ApplyForProject {
            get {
                return ResourceManager.GetString("ApplyForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncellemeni Artado Store&apos;da yayınlamak için başvur. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ApplyForUpdate {
            get {
                return ResourceManager.GetString("ApplyForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uygulama adı* benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uygulama Durumu: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AppStatus {
            get {
                return ResourceManager.GetString("AppStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yayıncı adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kapak fotoğrafı*: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *Dosya büyüklüğü maksimum 1MB olmalıdır. Önerilen boyut 1.024x500 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BannerLimit {
            get {
                return ResourceManager.GetString("BannerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beta Hakkında Sorulan Sorular benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BetaFAQFull {
            get {
                return ResourceManager.GetString("BetaFAQFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buna tam bir cevap veremeyiz. Fakat bir kaç ay boyunca Artado Store betada kalacak. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BetaFAQText1 {
            get {
                return ResourceManager.GetString("BetaFAQText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beta süreci boyunca tüm ürünler sadece ücretsiz olarak paylaşılacak. Beta bittikten sonra ücretli bir şekilde ürününüzü yayınlayabileceksiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BetaFAQText2 {
            get {
                return ResourceManager.GetString("BetaFAQText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beta süreci ne kadar sürecek? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BetaFAQTitle1 {
            get {
                return ResourceManager.GetString("BetaFAQTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado Store&apos;da ürünümü ücretli bir şekilde yayınlayabilir miyim? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BetaFAQTitle2 {
            get {
                return ResourceManager.GetString("BetaFAQTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado Store şu an beta sürecinde olduğundan uygulamanızı sadece ücretsiz olarak paylaşabilirsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BetaUnpaidWarning {
            get {
                return ResourceManager.GetString("BetaUnpaidWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado Store şu an beta sürecinde olduğundan bu sayfa şu anda herkese açık değildir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BetaWarning {
            get {
                return ResourceManager.GetString("BetaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hakkınızda benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yanlış kod! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CodeIncorrect {
            get {
                return ResourceManager.GetString("CodeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Koleksiyonlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-posta hesabınızı doğrulayın benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CreateAPI {
            get {
                return ResourceManager.GetString("CreateAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado servislerinden projelerinde yararlanmak için API oluştur. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CreateAPILong {
            get {
                return ResourceManager.GetString("CreateAPILong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uygulama Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CreateApp {
            get {
                return ResourceManager.GetString("CreateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oyun Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CreateGame {
            get {
                return ResourceManager.GetString("CreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proje Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Versiyon Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CreateVersion {
            get {
                return ResourceManager.GetString("CreateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Açıklama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bağış yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado&apos;ya bağış yaparak projelerimizi ayakta tutmamıza ve daha çok geliştirmemize yardımcı olabilirsiniz! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DonateText {
            get {
                return ResourceManager.GetString("DonateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Düzenle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-posta benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kodu girin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-postanıza gönderdiğimiz 6 haneli kodu girin. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EnterVerificationCode {
            get {
                return ResourceManager.GetString("EnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onay Kodunu Girin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EnterVerifyCode {
            get {
                return ResourceManager.GetString("EnterVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Etkinlikler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ExtensionFile {
            get {
                return ResourceManager.GetString("ExtensionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya büyüklüğü maksimum 1GB olmalıdır. &quot;.css&quot;, &quot;.js&quot; veya resim dosyası yükleyin. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ExtensionLimit {
            get {
                return ResourceManager.GetString("ExtensionLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eklenti benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ExtensionType {
            get {
                return ResourceManager.GetString("ExtensionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SSS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sıkça Sorulan Sorular benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FAQFull {
            get {
                return ResourceManager.GetString("FAQFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado Developers hesabı açarak ürününüzü Artado Store&apos;da paylaşabilirsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FAQText1 {
            get {
                return ResourceManager.GetString("FAQText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yaptığınız oyunları, uygulamaları, temaları ve Artado logolarını; Artado Store&apos;da paylaşabilirsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FAQText2 {
            get {
                return ResourceManager.GetString("FAQText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Hayır. Artado Store&apos;da ücretsiz şekilde 5 oyun ve 5 uygulama paylaşabilirsiniz. Yani toplamda 10 ürün paylaşabilirsiniz. Şu anda Artado Store beta sürecinde olduğundan 10&apos;dan fazla ürün paylaşamazsınız. Beta süreci bittikten sonra da 10&apos;dan fazla ürün paylaşmak için belli bir ücret ödemeniz gerekecek. Fakat tabi ki istisnalar yapılabilir. Beta sürecinde daha fazla ürün paylaşmak için bizimle iletişime geçebilirsiniz. Bu kısıtlama sadece oyun ve uygulamalarda geçerlidir. Workshop ürünlerinde(eklentiler, tema [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FAQText3 {
            get {
                return ResourceManager.GetString("FAQText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürünümü Artado Store&apos;da nasıl paylaşabilirim? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FAQTitle1 {
            get {
                return ResourceManager.GetString("FAQTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado Store&apos;da neler paylaşabilirim? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FAQTitle2 {
            get {
                return ResourceManager.GetString("FAQTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado Store&apos;da ürünümü paylaşmak için para ödemeli miyim? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FAQTitle3 {
            get {
                return ResourceManager.GetString("FAQTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Android için dosyalar: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FilesForAndroid {
            get {
                return ResourceManager.GetString("FilesForAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BSD için dosyalar: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FilesForBSD {
            get {
                return ResourceManager.GetString("FilesForBSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Haiku için dosyalar: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FilesForHaiku {
            get {
                return ResourceManager.GetString("FilesForHaiku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Linux için dosyalar: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FilesForLinux {
            get {
                return ResourceManager.GetString("FilesForLinux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MacOS için dosyalar: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FilesForMacOS {
            get {
                return ResourceManager.GetString("FilesForMacOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows için dosyalar: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FilesForWindows {
            get {
                return ResourceManager.GetString("FilesForWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *Dosya büyüklüğü maksimum 1GB olmalıdır. &quot;.zip&quot; veya Flatpak dosyası yükleyin. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FileTypeLinux {
            get {
                return ResourceManager.GetString("FileTypeLinux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *Dosya büyüklüğü maksimum 1GB olmalıdır. &quot;.zip&quot; veya &quot;.dmg&quot; dosyası yükleyin. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FileTypeMacOS {
            get {
                return ResourceManager.GetString("FileTypeMacOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *Dosya büyüklüğü maksimum 1GB olmalıdır. &quot;.zip&quot; dosyası yükleyin. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FileTypeOther {
            get {
                return ResourceManager.GetString("FileTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *Dosya büyüklüğü maksimum 1GB olmalıdır. &quot;.zip&quot; ve &quot;.exe&quot; dosyası yükleyin. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FileTypeWindows {
            get {
                return ResourceManager.GetString("FileTypeWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ücretsiz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oyun açıklaması: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GameDescription {
            get {
                return ResourceManager.GetString("GameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oyun türü: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GameGenre {
            get {
                return ResourceManager.GetString("GameGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado Store Beta sürümünde sadece 5 tane oyun yayınlamanıza izin verir. Oyun yayınlama sınırına ulaştınız. Bağış yaparak daha fazla oyun yayınlayabilirsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GameLimit {
            get {
                return ResourceManager.GetString("GameLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oyun adı*: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oyun Durumu: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GameStatus {
            get {
                return ResourceManager.GetString("GameStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aksiyon benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreAction {
            get {
                return ResourceManager.GetString("GenreAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macera benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreAdventure {
            get {
                return ResourceManager.GetString("GenreAdventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anime benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreAnime {
            get {
                return ResourceManager.GetString("GenreAnime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sanat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreArt {
            get {
                return ResourceManager.GetString("GenreArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kitaplar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreBooks {
            get {
                return ResourceManager.GetString("GenreBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreBusiness {
            get {
                return ResourceManager.GetString("GenreBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kart Oyunu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreCardGame {
            get {
                return ResourceManager.GetString("GenreCardGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eğitim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreEducation {
            get {
                return ResourceManager.GetString("GenreEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eğitici benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreEducational {
            get {
                return ResourceManager.GetString("GenreEducational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eğlence benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreEntertainment {
            get {
                return ResourceManager.GetString("GenreEntertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dövüş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreFight {
            get {
                return ResourceManager.GetString("GenreFight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finans benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreFinance {
            get {
                return ResourceManager.GetString("GenreFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yiyecekler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreFood {
            get {
                return ResourceManager.GetString("GenreFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arkadaşlık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreFriendship {
            get {
                return ResourceManager.GetString("GenreFriendship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sağlık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreHealth {
            get {
                return ResourceManager.GetString("GenreHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Korku benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreHorror {
            get {
                return ResourceManager.GetString("GenreHorror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MMO benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreMMO {
            get {
                return ResourceManager.GetString("GenreMMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müzik benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreMusic {
            get {
                return ResourceManager.GetString("GenreMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Haberler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreNews {
            get {
                return ResourceManager.GetString("GenreNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NSFW benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreNSFW {
            get {
                return ResourceManager.GetString("GenreNSFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diğer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreOther {
            get {
                return ResourceManager.GetString("GenreOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Platform benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenrePlatformer {
            get {
                return ResourceManager.GetString("GenrePlatformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bulmaca benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenrePuzzle {
            get {
                return ResourceManager.GetString("GenrePuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yarış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreRacing {
            get {
                return ResourceManager.GetString("GenreRacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RPG benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreRPG {
            get {
                return ResourceManager.GetString("GenreRPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simülasyon benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreSimulation {
            get {
                return ResourceManager.GetString("GenreSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sosyal benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreSocial {
            get {
                return ResourceManager.GetString("GenreSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreSport {
            get {
                return ResourceManager.GetString("GenreSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strateji benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreStrategy {
            get {
                return ResourceManager.GetString("GenreStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hayatta Kalma benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreSurvival {
            get {
                return ResourceManager.GetString("GenreSurvival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Araçlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreTools {
            get {
                return ResourceManager.GetString("GenreTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seyahat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreTravel {
            get {
                return ResourceManager.GetString("GenreTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Görsel Roman benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreVisualNovel {
            get {
                return ResourceManager.GetString("GenreVisualNovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hava durumu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenreWeather {
            get {
                return ResourceManager.GetString("GenreWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ana Sayfa benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Görüntüler*: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *Dosya büyüklüğü maksimum 5MB olmalıdır. Minimum 1 dosya yüklemelisiniz. Maksimum 5 dosya yükleyebilirsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImagesLimit {
            get {
                return ResourceManager.GetString("ImagesLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado Store ile oyununuzu veya uygulamanızı yayınlayın. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IntroText1 {
            get {
                return ResourceManager.GetString("IntroText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sitenizi Artado veri tabanına ekleyin ve SEO ayarlarınızı kontrol edin. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IntroText2 {
            get {
                return ResourceManager.GetString("IntroText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado veya Nova için yaptığınız temaları ve logoları insanlarla paylaşın. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IntroText3 {
            get {
                return ResourceManager.GetString("IntroText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürününüzü paylaşın benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IntroTitle1 {
            get {
                return ResourceManager.GetString("IntroTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sitenizi kontrol edin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IntroTitle2 {
            get {
                return ResourceManager.GetString("IntroTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sanatınızı paylaşın benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IntroTitle3 {
            get {
                return ResourceManager.GetString("IntroTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Katıl benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discord sunucumuza katılın benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string JoinDiscord {
            get {
                return ResourceManager.GetString("JoinDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oturum Aç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado Store&apos;da ürün yayınlamaya devam etmek için hesabına giriş yapmalısın. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hesabına Giriş Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logo*: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *Dosya büyüklüğü maksimum 1MB olmalıdır. Önerilen boyut 512x512 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LogoLimit {
            get {
                return ResourceManager.GetString("LogoLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logo benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LogoType {
            get {
                return ResourceManager.GetString("LogoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uygulamalarım benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MyApplications {
            get {
                return ResourceManager.GetString("MyApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oyunlarım benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MyGames {
            get {
                return ResourceManager.GetString("MyGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projelerim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MyProjects {
            get {
                return ResourceManager.GetString("MyProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proje açıklaması: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProjectDescription {
            get {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proje adı*: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proje Türü*: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProjectType {
            get {
                return ResourceManager.GetString("ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yayınla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uygulama Yayınla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PublishApp {
            get {
                return ResourceManager.GetString("PublishApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oyun Yayınla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PublishGame {
            get {
                return ResourceManager.GetString("PublishGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projeni Yayınla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PublishProject {
            get {
                return ResourceManager.GetString("PublishProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt ol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado Store&apos;da ürününü paylaşmak için bir geliştirici hesabı oluşturmalısın. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RegisterText {
            get {
                return ResourceManager.GetString("RegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geliştirici Hesabı Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaydet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ara benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tekrar gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SendAgain {
            get {
                return ResourceManager.GetString("SendAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ayarlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaynak Kodu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beta benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StatusBeta {
            get {
                return ResourceManager.GetString("StatusBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geliştirmede benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StatusIndev {
            get {
                return ResourceManager.GetString("StatusIndev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yayında benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StatusRelease {
            get {
                return ResourceManager.GetString("StatusRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3 veya daha fazla işletim sistemi destekleyen uygulamalar Artado Store&apos;da daha çok öne çıkar! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Support3OS {
            get {
                return ResourceManager.GetString("Support3OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Takım benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tema benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ThemeType {
            get {
                return ResourceManager.GetString("ThemeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oturum açarak &lt;a style=&quot;color: #E74646&quot; href=&quot;https://myacc.artado.xyz/tos&quot;&gt;Kullanım Şartları&lt;/a&gt; ve &lt;a style=&quot;color: #E74646&quot; href=&quot;https://myacc.artado.xyz/privacy&quot;&gt;Gizlilik Politikasını&lt;/a&gt; kabul etmiş olursunuz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TOSText {
            get {
                return ResourceManager.GetString("TOSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uygulama Güncelle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UpdateApp {
            get {
                return ResourceManager.GetString("UpdateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oyun Güncelle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UpdateGame {
            get {
                return ResourceManager.GetString("UpdateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projeni Güncelle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UpdateProject {
            get {
                return ResourceManager.GetString("UpdateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL*: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı adı ya da e-posta zaten alınmış. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UsernameOrEmailTaken {
            get {
                return ResourceManager.GetString("UsernameOrEmailTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onay Kodu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-posta hesabına gelen 6 haneli onay kodunu girin. Eğer kodu bulamazsanız spam ve çöp kutusunu kontrol etmeyi unutmayın. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VerifyText {
            get {
                return ResourceManager.GetString("VerifyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Versiyon numarası* benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sürümler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Versions {
            get {
                return ResourceManager.GetString("Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   En son yayınladığınız sürüm onaylanmadan yeni sürüm yayınlayamazsınız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WaitForUpdateApproval {
            get {
                return ResourceManager.GetString("WaitForUpdateApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Web sitesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado Developers hesabı ile Artado Store&apos;da uygulamanızı, oyununuzu ve sanatınızı insanlar ile paylaşabilirsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API detaylarınız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string YourAPIDetails {
            get {
                return ResourceManager.GetString("YourAPIDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya büyüklüğü maksimum 1GB olmalıdır.  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string _1GBLimit {
            get {
                return ResourceManager.GetString("1GBLimit", resourceCulture);
            }
        }
    }
}
